i hope to god this works
Decatur-Robotics/FRC-1984-Team-4026 pull request #2
Opened 2024-11-12 22:34 UTC by seankid

speak yo stuff owen🗣️🗣️🗣️🔥🔥🔥

2024-11-12 22:41 UTC, seankid commented
im pretty sure there's crucial stuff missing
but i dont know what it is

2024-11-12 22:53 UTC, Beckoe requested changes
A couple of small changes needed

2024-11-12 22:53 UTC, Beckoe commented on RobotCode/src/main/java/frc/robot/constants/Ports.java
> +    public static final int INTAKE_LEFT_MOTOR = 91021;
Set these all to 0, please.

2024-11-12 22:53 UTC, Beckoe commented on RobotCode/src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +	public void setDesiredRotation(double desiredRotation){
You still need to set the output of the motors in here.

2024-11-12 22:53 UTC, Beckoe commented on RobotCode/src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +	public void setDesiredVelocity(double desiredVelocity)
Rename this to just setVelocity because it is directly setting the velocity. Do the same for the rotation method above.

2024-11-12 22:53 UTC, Beckoe commented on RobotCode/src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +	public void setDesiredVelocity(double desiredVelocity)
When I say do the same, replace velocity with rotation of course.

2024-11-19 21:28 UTC, Beckoe approved these changes

2024-11-19 21:29 UTC, merged